import type { PricingTier } from "../types/pricing.types";

export const SPF_TIER_REGISTRY: PricingTier[] = [
  {
    id: "growth",
    name: "Growth Pack",
    tagline: "Ideal for local organizers, regional live streams, and expanding creators.",
    baseMonthlyPrice: 79,
    overageRatePerMinute: 0.15,
    isPopular: false,
    limits: {
      liveMinutesIncluded: 500,
      maxLanguages: 5,
      maxFileSizeMb: 25,
      maxDocsPerMonth: 50,
      hasHumanOverrideCanvas: false,
      dedicatedHardwareAvailable: false,
    },
    includedFeatures: [
      "Everything in Free Sandbox",
      "Automatic Captions & Translation",
      "Audio Live Streaming",
      "Document Translation Portal (up to 50 docs/mo)",
      "Custom Vocabulary Profiles (Up to 3 Glossaries)",
      "Zoom & YouTube Integration",
    ],
    supportTier: "Standard Developer Business Hours Email Service (24h SLA)",
  },
  {
    id: "scale",
    name: "Scale Enterprise",
    tagline: "Built for corporate deployments, international events, and high-volume usage.",
    baseMonthlyPrice: 299,
    overageRatePerMinute: 0.1,
    isPopular: true,
    limits: {
      liveMinutesIncluded: 2500,
      maxLanguages: 100,
      maxFileSizeMb: 100,
      maxDocsPerMonth: 500,
      hasHumanOverrideCanvas: true,
      dedicatedHardwareAvailable: false,
    },
    includedFeatures: [
      "Everything in Growth Pack",
      "Multilingual Conversations (Meetings & Workshops)",
      "Multilingual Polls",
      "Slides Translation",
      "Audio Video Captions & Subtitles",
      "Human-in-the-Loop Intercept Correction Canvas",
      "Unlimited Structural Glossary Engine Instances",
      "Multi-User Collaborative Workspace",
    ],
    supportTier: "Priority Executive Support Channels (4h SLA Escalation)",
  },
  {
    id: "enterprise",
    name: "Contact Sales",
    tagline: "Tailored architecture with dedicated environments for high compliance.",
    baseMonthlyPrice: 1200,
    overageRatePerMinute: 0.05,
    isPopular: false,
    limits: {
      liveMinutesIncluded: 10000,
      maxLanguages: 100,
      maxFileSizeMb: 1000,
      maxDocsPerMonth: 9999,
      hasHumanOverrideCanvas: true,
      dedicatedHardwareAvailable: true,
    },
    includedFeatures: [
      "Everything in Scale Enterprise",
      "Isolated Computing Environments",
      "Custom Language Model (LLM) Micro-Tuning",
      "Enterprise Single-Sign-On Protocols (SAML/OIDC)",
      "Strict Regulatory Compliance Guardrails",
      "Dedicated Hardware Allocation",
      "Custom API Integrations",
      "White-Label Options",
    ],
    supportTier: "Dedicated Solutions Engineer Engagement (99.99% Uptime Guarantee)",
  },
];
